language: python
python:
  - 2.6
  - 2.7
  - 3.2
env:
  - "DJANGO='https://github.com/django/django/tarball/master'"
  - "DJANGO='Django>=1.4,<1.5'"
  - "DJANGO='Django>=1.3,<1.4'"
  - "DJANGO='Django>=1.2,<1.3'"
install:
  - pip install -q https://github.com/dag/attest/tarball/master six $DJANGO \
      --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - DJANGO_SETTINGS_MODULE=tests.settings attest -r django tests
